name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site with production config
        run: bundle exec jekyll build --config _config_prod.yml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Rama donde se desplegará el sitio
          folder: _site  # Carpeta de salida de Jekyll
